name: .NET Build & Test

on:
  push:
    branches: [ main ]   #Run this workflow when code is pushed to the main branch
  pull_request:
    branches: [ main ]  #Also run workflow when there are PR targetin "Main"

jobs:
  build:
    runs-on: ubuntu-latest #Job runs on a Ubuntu Linux VM hosted by GitHub

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3 #Downloads and installs the correct .NET version
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet-packages
      run: dotnet restore #Restore all packages declared in .csproj or .sln files

    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal #Runs all unitTest in the solution
