name: .NET Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Pawsistant.sln

    - name: Build (Release)
      run: dotnet build Pawsistant.sln --configuration Release --no-restore

    - name: Test (PawsistantTest)
      run: dotnet test ./PawsistantTest/PawsistantTest.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/**/*.trx'
